apiVersion: v1
kind: Pod
metadata:
  name: dbdemo
  namespace: default
spec:
  containers:
  - name: pg
    image: postgres:9.6
    env:
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: dbconfig
            key: user
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: dbconfig
            key: db
